repos:
  url_shortener:
    main:
      string_input: "value-for-main"
      another_string: "hello"
      bool_input: true
      another_bool: false
    develop:
      string_input: "value-for-develop"
      another_string: "dev-hello"
      bool_input: false
      another_bool: true
