name: Reusable Workflow

on:
  workflow_call:
    inputs:
      config_path:
        required: false
        type: string
        default: '.github/workflow-config.yaml'
      string_input:
        required: false
        type: string
      another_string:
        required: false
        type: string
      bool_input:
        required: false
        type: string
      another_bool:
        required: false
        type: string

jobs:
  resolve-config:
    runs-on: ubuntu-latest
    outputs:
      string_input: ${{ steps.set-outputs.outputs.string_input }}
      another_string: ${{ steps.set-outputs.outputs.another_string }}
      bool_input: ${{ steps.set-outputs.outputs.bool_input }}
      another_bool: ${{ steps.set-outputs.outputs.another_bool }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout reusable workflow repo
        uses: actions/checkout@v4
        with:
          repository: ruskinb1/test-passing-secret
          ref: main
          path: reusable-repo

      - name: Download yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Fetch values from config or inputs
        id: set-outputs
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          branch="${GITHUB_REF##*/}"
          config_path="reusable-repo/.github/workflow-config.yaml"
      
          declare -A input_vars=(
            [string_input]="${{ inputs.string_input }}"
            [another_string]="${{ inputs.another_string }}"
            [bool_input]="${{ inputs.bool_input }}"
            [another_bool]="${{ inputs.another_bool }}"
          )
      
          for key in "${!input_vars[@]}"; do
            config_value=$(yq e ".repos.\"$repo\".\"$branch\".$key" "$config_path")
            value="${input_vars[$key]}"
            [[ -z "$value" || "$value" == 'null' ]] && value="$config_value"
            echo "$key=$value" >> $GITHUB_OUTPUT
          done

  call-callee:
    needs: resolve-config
    uses: ./.github/workflows/callee.yml
    with:
      string_input: ${{ needs.resolve-config.outputs.string_input }}
      another_string: ${{ needs.resolve-config.outputs.another_string }}
      bool_input: ${{ fromJSON(needs.resolve-config.outputs.bool_input) }}
      another_bool: ${{ fromJSON(needs.resolve-config.outputs.another_bool) }}
