name: Reusable Workflow

on:
  workflow_call:
    inputs:
      config_path:
        required: false
        type: string
        default: '.github/workflow-config.yaml'
      string_input:
        required: false
        type: string
      another_string:
        required: false
        type: string
      bool_input:
        required: false
        type: string
      another_bool:
        required: false
        type: string

jobs:
  resolve-config:
    runs-on: ubuntu-latest
    outputs:
      string_input: ${{ steps.set-outputs.outputs.string_input }}
      another_string: ${{ steps.set-outputs.outputs.another_string }}
      bool_input: ${{ steps.set-outputs.outputs.bool_input }}
      another_bool: ${{ steps.set-outputs.outputs.another_bool }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Fetch values from config
        id: set-outputs
        run: |
          repo="${GITHUB_REPOSITORY##*/}"
          branch="${GITHUB_REF##*/}"
          config_path="${{ inputs.config_path }}"
          string_input=$(yq e ".repos.\"$repo\".\"$branch\".string_input" "$config_path")
          another_string=$(yq e ".repos.\"$repo\".\"$branch\".another_string" "$config_path")
          bool_input=$(yq e ".repos.\"$repo\".\"$branch\".bool_input" "$config_path")
          another_bool=$(yq e ".repos.\"$repo\".\"$branch\".another_bool" "$config_path")
          echo "string_input=$string_input" >> $GITHUB_OUTPUT
          echo "another_string=$another_string" >> $GITHUB_OUTPUT
          echo "bool_input=$bool_input" >> $GITHUB_OUTPUT

          echo "another_bool=$another_bool" >> $GITHUB_OUTPUT

  call-callee:
    needs: resolve-config
    uses: ./.github/workflows/callee.yml
    with:
      string_input: ${{ needs.resolve-config.outputs.string_input }}
      another_string: ${{ needs.resolve-config.outputs.another_string }}
      bool_input: ${{ fromJSON(needs.resolve-config.outputs.bool_input) }}
      another_bool: ${{ fromJSON(needs.resolve-config.outputs.another_bool) }}
