name: Test Dynamic Workflow

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        default: 'l'
      tags:
        description: 'Test scenario tags'
        default: ''

jobs:
  list-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: List Input Keys
        if: ${{ github.run_attempt == 1 }}
        env:
          INPUTS_JSON: ${{ toJSON(inputs) }}
        run: echo "$INPUTS_JSON"
